### ISSUE TITLE
scroll bar appearance

### ISSUE THREAD

**Issue by alfredpaldezgit** [icelam/random-name-picker#1] opened 2022-05-05 14:18 UTC
scroll bar appearing when a winner is chosen.

**Comment by icelam** [comment] 2022-05-05 15:21
Hi @alfredpaldezgit, I couldn't reproduce the issue you mentioned. Can you provide more information on the operation system, browser and screen resolution you are using?

Here is what it looks like on a 13-inch MacBook Pro with 1440x900px resolution using Chromium based browser:
https://user-images.githubusercontent.com/6780420/166955898-507bab01-4646-44fb-b74c-f879b3473d67.mp4

**Comment by icelam** [comment] 2022-05-26 07:06
Closing this as I was able to reproduce the issue. 
I was suspecting it is the same issue I had resolved in release 1.1.0, and it might just be a browser cache or PWA cache.

Welcome to reopen this if you still have the issue.

**Closed as completed by icelam** 2022-05-26 07:06 UTC
